services:
  postgresdb:
    image: postgres

    restart: always

    ports:
      - "5432:5432"

    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: FTMO_DEMO
      

  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: "said@mail.com"
      PGADMIN_DEFAULT_PASSWORD: 1234

    ports: 
      - '80:80'

    depends_on:
      - postgresdb
