"""Agrego tablas de portfolios

Revision ID: 028cb92a62fb
Revises: 5b8bc612c329
Create Date: 2025-01-28 16:55:49.161735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028cb92a62fb'
down_revision: Union[str, None] = '5b8bc612c329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Portfolios',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('PortfoliosBacktests',
    sa.Column('PortfolioId', sa.UUID(), nullable=False),
    sa.Column('BacktestId', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('PortfolioId', 'BacktestId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PortfoliosBacktests')
    op.drop_table('Portfolios')
    # ### end Alembic commands ###
