"""Agrego claves foraneas de portfolios

Revision ID: 12a9aadddd5e
Revises: 028cb92a62fb
Create Date: 2025-01-28 17:04:41.943109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a9aadddd5e'
down_revision: Union[str, None] = '028cb92a62fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfoliosBacktests', sa.Column('BotPerformanceId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'PortfoliosBacktests', 'BotPerformances', ['BotPerformanceId'], ['Id'])
    op.create_foreign_key(None, 'PortfoliosBacktests', 'Portfolios', ['PortfolioId'], ['Id'])
    op.drop_column('PortfoliosBacktests', 'BacktestId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfoliosBacktests', sa.Column('BacktestId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'PortfoliosBacktests', type_='foreignkey')
    op.drop_constraint(None, 'PortfoliosBacktests', type_='foreignkey')
    op.drop_column('PortfoliosBacktests', 'BotPerformanceId')
    # ### end Alembic commands ###
