"""Fix relationships

Revision ID: 16ded952a52d
Revises: 7452781d8a8e
Create Date: 2025-01-21 16:00:56.680209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ded952a52d'
down_revision: Union[str, None] = '7452781d8a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RandomTests', sa.Column('Iterations', sa.Integer(), nullable=False))
    op.drop_column('RandomTests', 'TradesPercentToRemove')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RandomTests', sa.Column('TradesPercentToRemove', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('RandomTests', 'Iterations')
    # ### end Alembic commands ###
