"""Agrego Id a la tabla PortfolioBacktest

Revision ID: 5a15a0aefea7
Revises: 12a9aadddd5e
Create Date: 2025-01-30 04:16:31.709671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a15a0aefea7'
down_revision: Union[str, None] = '12a9aadddd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfoliosBacktests', sa.Column('Id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PortfoliosBacktests', 'Id')
    # ### end Alembic commands ###
