"""Agrego columna favorite

Revision ID: 5b8bc612c329
Revises: da1c8afd8e99
Create Date: 2025-01-27 12:39:37.562139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8bc612c329'
down_revision: Union[str, None] = 'da1c8afd8e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Añade la columna como nullable temporalmente
    op.add_column('BotPerformances', sa.Column('Favorite', sa.Boolean(), nullable=True))
    
    # 2. Actualiza todos los registros existentes para que tengan valor False
    op.execute('UPDATE "BotPerformances" SET "Favorite" = False')
    
    # 3. Cambia la columna para que no permita nulos
    op.alter_column('BotPerformances', 'Favorite', nullable=False)
    
    # 4. Elimina la columna 'Robust' (según tu comando inicial)
    op.drop_column('BotPerformances', 'Robust')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BotPerformances', sa.Column('Robust', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('BotPerformances', 'Favorite')
    # ### end Alembic commands ###
