"""Agrego columnas topBest y topworst en Trades

Revision ID: 6af01a7676fa
Revises: 52ec56d538e6
Create Date: 2025-01-18 13:28:32.346164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af01a7676fa'
down_revision: Union[str, None] = '52ec56d538e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trades', sa.Column('TopBest', sa.Boolean(), nullable=True))
    op.add_column('Trades', sa.Column('TopWorst', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Trades', 'TopWorst')
    op.drop_column('Trades', 'TopBest')
    # ### end Alembic commands ###
