"""Agrego tabla randomTest

Revision ID: 7452781d8a8e
Revises: 800c23632e73
Create Date: 2025-01-21 15:39:54.099049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7452781d8a8e'
down_revision: Union[str, None] = '800c23632e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RandomTests',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('BotPerformanceId', sa.UUID(), nullable=False),
    sa.Column('RandomTestPerformanceId', sa.UUID(), nullable=False),
    sa.Column('TradesPercentToRemove', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['BotPerformanceId'], ['BotPerformances.Id'], ),
    sa.ForeignKeyConstraint(['RandomTestPerformanceId'], ['BotPerformances.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RandomTests')
    # ### end Alembic commands ###
