"""Agrego columna hours a timeframe

Revision ID: 800c23632e73
Revises: fc6101389c42
Create Date: 2025-01-20 23:13:58.987277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800c23632e73'
down_revision: Union[str, None] = 'fc6101389c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Timeframes', sa.Column('Hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Timeframes', 'Hours')
    # ### end Alembic commands ###
