"""Agrego tabla de montecarlo

Revision ID: 899215aaff2f
Revises: 53da7ed9ec44
Create Date: 2025-01-20 12:40:27.013345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899215aaff2f'
down_revision: Union[str, None] = '53da7ed9ec44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MontecarloTests',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('BotPerformanceId', sa.UUID(), nullable=False),
    sa.Column('Simulations', sa.Integer(), nullable=False),
    sa.Column('ThresholdRuin', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['BotPerformanceId'], ['BotPerformances.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('MetricsWarehouse', sa.Column('MontecarloTestId', sa.UUID(), nullable=False))
    op.drop_constraint('MetricsWarehouse_BotPerformanceId_fkey', 'MetricsWarehouse', type_='foreignkey')
    op.create_foreign_key(None, 'MetricsWarehouse', 'MontecarloTests', ['MontecarloTestId'], ['Id'])
    op.drop_column('MetricsWarehouse', 'BotPerformanceId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MetricsWarehouse', sa.Column('BotPerformanceId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'MetricsWarehouse', type_='foreignkey')
    op.create_foreign_key('MetricsWarehouse_BotPerformanceId_fkey', 'MetricsWarehouse', 'BotPerformances', ['BotPerformanceId'], ['Id'])
    op.drop_column('MetricsWarehouse', 'MontecarloTestId')
    op.drop_table('MontecarloTests')
    # ### end Alembic commands ###
