"""Agrego clase timeframe y relaciones con bot

Revision ID: 8a2c442191f9
Revises: 97926bc17207
Create Date: 2025-01-11 11:52:49.080731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2c442191f9'
down_revision: Union[str, None] = '97926bc17207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Timeframes',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('MetaTraderNumber', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('Bots', sa.Column('Id', sa.UUID(), nullable=False))
    op.add_column('Bots', sa.Column('StrategyId', sa.UUID(), nullable=True))
    op.add_column('Bots', sa.Column('TickerId', sa.UUID(), nullable=True))
    op.add_column('Bots', sa.Column('TimeframeId', sa.UUID(), nullable=True))
    op.add_column('Bots', sa.Column('Name', sa.String(), nullable=False))
    op.add_column('Bots', sa.Column('MetaTraderName', sa.String(length=16), nullable=False))
    op.add_column('Bots', sa.Column('Risk', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'Bots', 'Tickers', ['TickerId'], ['Id'])
    op.create_foreign_key(None, 'Bots', 'Timeframes', ['TimeframeId'], ['Id'])
    op.create_foreign_key(None, 'Bots', 'Strategies', ['StrategyId'], ['Id'])
    op.drop_column('Bots', 'id')
    op.drop_column('Bots', 'metatrader_name')
    op.drop_column('Bots', 'ticker')
    op.drop_column('Bots', 'strategy_name')
    op.drop_column('Bots', 'timeframe')
    op.drop_column('Bots', 'risk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Bots', sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Bots', sa.Column('strategy_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Bots', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Bots', sa.Column('metatrader_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Bots', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_constraint(None, 'Bots', type_='foreignkey')
    op.drop_column('Bots', 'Risk')
    op.drop_column('Bots', 'MetaTraderName')
    op.drop_column('Bots', 'Name')
    op.drop_column('Bots', 'TimeframeId')
    op.drop_column('Bots', 'TickerId')
    op.drop_column('Bots', 'StrategyId')
    op.drop_column('Bots', 'Id')
    op.drop_table('Timeframes')
    # ### end Alembic commands ###
