"""cambio risk de lugar

Revision ID: 8bf9de6c661a
Revises: d505bede3886
Create Date: 2025-01-15 10:42:03.012513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf9de6c661a'
down_revision: Union[str, None] = 'd505bede3886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'BotTradePerformances', ['BotPerformanceId'])
    op.add_column('Bots', sa.Column('Risk', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'Risk')
    op.drop_constraint(None, 'BotTradePerformances', type_='unique')
    # ### end Alembic commands ###
