"""Fix relationships

Revision ID: 920a5111b362
Revises: a23159ba9d81
Create Date: 2025-01-16 10:44:23.218284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920a5111b362'
down_revision: Union[str, None] = 'a23159ba9d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BotPerformances', 'Trades')
    op.add_column('Trades', sa.Column('BotPerformanceId', sa.UUID(), nullable=False))
    op.drop_constraint('Trades_BacktestId_fkey', 'Trades', type_='foreignkey')
    op.create_foreign_key(None, 'Trades', 'BotPerformances', ['BotPerformanceId'], ['Id'])
    op.drop_column('Trades', 'BacktestId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trades', sa.Column('BacktestId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Trades', type_='foreignkey')
    op.create_foreign_key('Trades_BacktestId_fkey', 'Trades', 'BotPerformances', ['BacktestId'], ['Id'])
    op.drop_column('Trades', 'BotPerformanceId')
    op.add_column('BotPerformances', sa.Column('Trades', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
