"""Agrego entidades

Revision ID: 97926bc17207
Revises: 9953a95e5b14
Create Date: 2025-01-10 22:11:39.008960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97926bc17207'
down_revision: Union[str, None] = '9953a95e5b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Tickers',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('CategoryId', sa.UUID(), nullable=True),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Commission', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tickers')
    op.drop_table('Categories')
    # ### end Alembic commands ###
