"""Agrego entidades, cambio id por Id en Strategy

Revision ID: 9953a95e5b14
Revises: 178a80c65f0c
Create Date: 2025-01-10 22:07:04.427960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9953a95e5b14'
down_revision: Union[str, None] = '178a80c65f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('Strategies', 'id', new_column_name='Id')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Strategies', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('Strategies', 'Id')
    # ### end Alembic commands ###
