"""Agrego clase trade

Revision ID: a23159ba9d81
Revises: e7be8fb2c516
Create Date: 2025-01-16 10:28:25.083239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23159ba9d81'
down_revision: Union[str, None] = 'e7be8fb2c516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trades',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('BacktestId', sa.UUID(), nullable=False),
    sa.Column('Size', sa.Integer(), nullable=False),
    sa.Column('EntryBar', sa.Integer(), nullable=False),
    sa.Column('ExitBar', sa.Integer(), nullable=False),
    sa.Column('EntryPrice', sa.Float(), nullable=False),
    sa.Column('ExitPrice', sa.Float(), nullable=False),
    sa.Column('PnL', sa.Float(), nullable=False),
    sa.Column('ReturnPct', sa.Float(), nullable=False),
    sa.Column('EntryTime', sa.Date(), nullable=False),
    sa.Column('ExitTime', sa.Date(), nullable=False),
    sa.Column('Duration', sa.Integer(), nullable=False),
    sa.Column('Equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['BacktestId'], ['BotPerformances.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trades')
    # ### end Alembic commands ###
