"""Agrego initial cash en bot_performances

Revision ID: ab363cb5ad5f
Revises: 6af01a7676fa
Create Date: 2025-01-18 13:45:04.854960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab363cb5ad5f'
down_revision: Union[str, None] = '6af01a7676fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BotPerformances', sa.Column('InitialCash', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BotPerformances', 'InitialCash')
    # ### end Alembic commands ###
