"""Fix relationships

Revision ID: b29d5c70e310
Revises: 920a5111b362
Create Date: 2025-01-16 11:18:55.915708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29d5c70e310'
down_revision: Union[str, None] = '920a5111b362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BotPerformances', sa.Column('Trades', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BotPerformances', 'Trades')
    # ### end Alembic commands ###
