"""Agrego REALMENTEE la tabla bot_trade_performance

Revision ID: d505bede3886
Revises: f0569540cf0e
Create Date: 2025-01-14 10:10:04.367164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd505bede3886'
down_revision: Union[str, None] = 'f0569540cf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BotTradePerformances',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('BotPerformanceId', sa.UUID(), nullable=True),
    sa.Column('MeanWinningReturnPct', sa.Float(), nullable=False),
    sa.Column('StdWinningReturnPct', sa.Float(), nullable=False),
    sa.Column('MeanLosingReturnPct', sa.Float(), nullable=False),
    sa.Column('StdLosingReturnPct', sa.Float(), nullable=False),
    sa.Column('MeanTradeDuration', sa.Float(), nullable=False),
    sa.Column('StdTradeDuration', sa.Float(), nullable=False),
    sa.Column('LongWinrate', sa.Float(), nullable=False),
    sa.Column('WinLongMeanReturnPct', sa.Float(), nullable=False),
    sa.Column('WinLongStdReturnPct', sa.Float(), nullable=False),
    sa.Column('LoseLongMeanReturnPct', sa.Float(), nullable=False),
    sa.Column('LoseLongStdReturnPct', sa.Float(), nullable=False),
    sa.Column('ShortWinrate', sa.Float(), nullable=False),
    sa.Column('WinShortMeanReturnPct', sa.Float(), nullable=False),
    sa.Column('WinShortStdReturnPct', sa.Float(), nullable=False),
    sa.Column('LoseShortMeanReturnPct', sa.Float(), nullable=False),
    sa.Column('LoseShortStdReturnPct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['BotPerformanceId'], ['BotPerformances.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BotTradePerformances')
    # ### end Alembic commands ###
