"""Agrego tabla bot_performance

Revision ID: f0569540cf0e
Revises: 8a2c442191f9
Create Date: 2025-01-13 23:03:28.009895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0569540cf0e'
down_revision: Union[str, None] = '8a2c442191f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BotPerformances',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('BotId', sa.UUID(), nullable=True),
    sa.Column('DateFrom', sa.Date(), nullable=False),
    sa.Column('DateTo', sa.Date(), nullable=False),
    sa.Column('Risk', sa.Float(), nullable=False),
    sa.Column('Method', sa.String(), nullable=False),
    sa.Column('StabilityRatio', sa.Float(), nullable=False),
    sa.Column('Trades', sa.Integer(), nullable=False),
    sa.Column('Return', sa.Float(), nullable=False),
    sa.Column('Drawdown', sa.Float(), nullable=False),
    sa.Column('RreturnDd', sa.Float(), nullable=False),
    sa.Column('CustomMetric', sa.Float(), nullable=False),
    sa.Column('WinRate', sa.Float(), nullable=False),
    sa.Column('Duration', sa.Integer(), nullable=False),
    sa.Column('Robust', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['BotId'], ['Bots.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_column('Bots', 'Risk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('Risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('BotPerformances')
    # ### end Alembic commands ###
