models: [
  # 'random_forest', 
  'gradient_boosting',
  # 'neural_network'
]

train_window: [
  # 1440, # tres meses
  # 1200, # dos meses
  960, # dos meses
  # 720, # mes y medio
  # 360, # tres semanas 
  # 480, # un mes
  # 240, # dos semanas
  # 120, # una semana
] # tamanio de la ventana de entrenamiento

train_period: [
  24, 
] # frecuencia con la que se entrena

stop_loss_in_pips: [
  # 5,
  10,
  # 15,
  # 20,
  # 25
]

risk_reward_ratio: [
  2,
  3,
  # 4,
  # 5,
  # 6, 
  # 7,
  # 8,
  # 9
]

periods_forward_target: [
  # 3,
  5,
  # 8,
  # 10,
]

use_days_in_position: [
  # True,
  False
]

trading_strategy: [
  # 'backbone.strategies.macd_strategy',
  'backbone.strategies.ml_strategy', 
  'backbone.strategies.bband_strategy', 
  # 'backbone.strategies.bband_macd_strategy', 
]