models: [
  null, 
  # 'random_forest', 
  # 'gradient_boosting',
  # 'neural_network'
]

train_window: [
  11520, # dos anios
  # 5760, # un anio
  # 1920, # cuatro meses
  # 1440, # tres meses
  # 1200, # dos meses y medio
  # 960, # dos meses
  # 720, # mes y medio
  # 480, # un mes
  # 360, # tres semanas 
  # 240, # dos semanas
  # 120, # una semana
] # tamanio de la ventana de entrenamiento

train_period: [
  24, 
  # 168, 
  # 480, 
] # frecuencia con la que se entrena

stop_loss_in_pips: [
  # 3,
  # 5,
  # 8,
  # 10,
  # 15,
  20,
  # 25,
]

risk_reward_ratio: [
  # 0.5,
  1,
  # 2,
  # 3,
  # 4,
  # 5,
  # 6, 
  # 7,
  # 8,
  # 9
]

periods_forward_target: [
  # 4,
  # 8,
  # 12,
  # 16,
  24,
  # 48,
  # 10,
]

trading_strategy: [
  'backbone.strategies.grid_smi.GridSmiAdx',
]

intervals: [
  2,
  # 4,
  # 6,
  # 8
]

trades_to_increment_risks: [
  # 1,
  2,
  # 3,
  # 4
]


leverages: [
  # 100,
  # 200,
  500,
]

risk_percentages: [
  # 5, 
  # 10, 
  15, 
  # 20, 
  # 30, 
  # 40, 
  # 50, 
  # 60
]