models: [
  'random_forest', 
]

train_window: [
  # 720, # mes y medio
  # 480, # un mes
  360 # tres semanas
  # 240, # dos semanas
  # 120, # una semana
] # tamanio de la ventana de entrenamiento

train_period: [
  1, 
] # frecuencia con la que se entrena

stop_loss_in_pips: [
  15, 
]

take_profits_in_pips: [
  30,
]

periods_forward_target: [
  5,
  # 10,
  # 15,
]

use_days_in_position: [
  # True,
  False
]

trading_strategy: [
  'backbone.strategies.macd_strategy',
  # 'backbone.strategies.bband_strategy', 
]