# GD -- PA -- FA -- RT
#             |__  MC

# GD -- PA -- RT
#        |__  MC

get_data:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  out_path: './backtesting_pipeline/get_data'

preliminar_analysis:
  run_only_in: null
  strategy_path: 'backbone.b_percent_strategy.BPercent'
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  in_path: './backtesting_pipeline/get_data'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/preliminar_analysis'

full_analysis:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  strategy_path: 'backbone.b_percent_strategy.BPercent'
  opt_params:
    b_open_threshold : [0.9, 0.95, 1, 1.5]
    b_close_threshold: [0.2, 0.5, 0.6, 0.8, 0.9, 1]

# ADVERTENCIA asegurarse que warmup_bars es el mayor valor de parametro para indicadores que tenga la estrategia
  warmup_bars: 200
  validation_bars: 200
  data_path: './backtesting_pipeline/get_data'
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/preliminar_analysis'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/wfo'

choose_the_best:
  preliminar_analysis_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/preliminar_analysis'
  full_analysis_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/wfo'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/choose_the_best'

montecarlo:
  run_only_in: null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/choose_the_best'
  strategy_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}'
  n_simulations: 1000
  threshold_ruin: 0.9
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/montecarlo'

random_test:
  run_only_in: null
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  n_iterations: 10
  strategy_path: 'backbone.random_trader.RandomTrader'
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/choose_the_best'
  data_path: './backtesting_pipeline/get_data'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/random_test'

luck_test:
  run_only_in: null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/choose_the_best'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}'
  trades_percent_to_remove: 3
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/luck_test'

correlation_test:
  run_only_in: null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/choose_the_best'
  data_path: './backtesting_pipeline/get_data'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/{risk}/correlation_test'
  show: True

