# GD -- PA -- FA -- RT
#             |__  MC

# GD -- PA -- RT
#        |__  MC

get_data:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  out_path: './backtesting_pipeline/get_data'

preliminar_analysis:
  strategy_path: 'backbone.adx_di.AdxDi'
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  in_path: './backtesting_pipeline/get_data'
  out_path: 'backtesting_pipeline/AdxDi/preliminar_analysis'

full_analysis:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  strategy_path: 'backbone.adx_di.AdxDi'
  opt_params:
    adx_threshold: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

# ADVERTENCIA asegurarse que warmup_bars es el mayor valor de parametro para indicadores que tenga la estrategia
  warmup_bars: 14
  validation_bars: 200
  data_path: './backtesting_pipeline/get_data'
  in_path: 'backtesting_pipeline/AdxDi/preliminar_analysis'
  out_path: 'backtesting_pipeline/AdxDi/wfo'

random_test:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  strategy_path: 'backbone.random_trader.RandomTrader'
  data_path: './backtesting_pipeline/get_data'
  in_path: 'backtesting_pipeline/AdxDi/preliminar_analysis'
  out_path: 'backtesting_pipeline/AdxDi/random_test'

montecarlo:
  in_path: 'backtesting_pipeline/AdxDi/wfo'
  n_simulations: 100
  initial_equity: 10000
  threshold_ruin: 0.9
  out_path: 'backtesting_pipeline/AdxDi/montecarlo'


