# GD -- PA -- FA -- RT
#             |__  MC

# GD -- PA -- RT
#        |__  MC

get_data:
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  out_path: './backtesting_pipeline/get_data'

preliminar_analysis:
  strategy_path: 'backbone.triple_sma.TripleSMA'
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  in_path: './backtesting_pipeline/get_data'
  out_path: 'backtesting_pipeline/strategies/TripleSMA/preliminar_analysis'

montecarlo:
  run_only_in: ['GBPUSD_16385','US2000.cash_16385','USDCHF_16386'] #null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/preliminar_analysis'
  strategy_path: 'backtesting_pipeline/strategies/{strategy_name}'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}'
  n_simulations: 1000
  threshold_ruin: 0.9
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/montecarlo'

random_test:
  run_only_in: ['GBPUSD_16385','US2000.cash_16385','USDCHF_16386'] #null
  date_from: '2021-01-01'
  date_to: '2024-11-01'
  n_iterations: 30
  strategy_path: 'backbone.random_trader.RandomTrader'
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/preliminar_analysis'
  data_path: './backtesting_pipeline/get_data'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/random_test'

luck_test:
  run_only_in: ['GBPUSD_16385','US2000.cash_16385','USDCHF_16386'] #null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/preliminar_analysis'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}'
  trades_percent_to_remove: 3
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/luck_test'

  correlation_test:
  run_only_in: ['GBPUSD_16385','US2000.cash_16385','USDCHF_16386'] #null
  in_path: 'backtesting_pipeline/strategies/{strategy_name}/choose_the_best'
  data_path: './backtesting_pipeline/get_data'
  root_path: 'backtesting_pipeline/strategies/{strategy_name}'
  out_path: 'backtesting_pipeline/strategies/{strategy_name}/correlation_test'
  show: True